spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.202.67:3306/imooc-demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  session:
    store-type: none
  redis:
    host: 47.102.202.67
    port: 6379
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
security:
  basic:
    enabled: false